apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secrets
type: Opaque
data:
  databaseUrl: {{ .Values.database.url | b64enc | quote }}
  jwtSecret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  betterAuthSecret: {{ .Values.secrets.betterAuthSecret | b64enc | quote }}