"""add_due_date_and_recurrence

Revision ID: 140a8a452d6a
Revises: bc9f6062c35c
Create Date: 2025-12-30 13:32:59.623079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '140a8a452d6a'
down_revision: Union[str, None] = 'bc9f6062c35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    recurrence_enum = sa.Enum('none', 'daily', 'weekly', 'monthly', name='recurrenceenum')
    recurrence_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence', recurrence_enum, nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE tasks SET recurrence = 'none' WHERE recurrence IS NULL")
    
    # Make recurrence NOT NULL
    op.alter_column('tasks', 'recurrence', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence')
    op.drop_column('tasks', 'due_date')
    
    # Drop the enum type
    sa.Enum(name='recurrenceenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
