"""Add priorities and tags

Revision ID: 81b8525ff879
Revises: bc12dbf8986d
Create Date: 2025-12-26 18:13:17.503377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81b8525ff879'
down_revision: Union[str, None] = 'bc12dbf8986d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    priority_enum = sa.Enum('low', 'medium', 'high', name='priorityenum')
    priority_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('tags',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_tag_links',
    sa.Column('task_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'tag_id')
    )
    op.add_column('tasks', sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priorityenum'), nullable=False, server_default='medium'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    op.drop_table('task_tag_links')
    op.drop_table('tags')
    # ### end Alembic commands ###
