"""add_completed_at_and_notifications

Revision ID: ac64cf3d3755
Revises: 140a8a452d6a
Create Date: 2025-12-30 16:04:34.416561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac64cf3d3755'
down_revision: Union[str, None] = '140a8a452d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('type', sa.Enum('TASK_DUE', 'TASK_OVERDUE', 'RECURRING_SPAWNED', 'GENERAL', name='notificationtype'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_group_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.alter_column('tasks', 'recurrence',
               existing_type=postgresql.ENUM('none', 'daily', 'weekly', 'monthly', name='recurrenceenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'recurrence',
               existing_type=postgresql.ENUM('none', 'daily', 'weekly', 'monthly', name='recurrenceenum'),
               nullable=False)
    op.drop_column('tasks', 'recurrence_group_id')
    op.drop_column('tasks', 'completed_at')
    op.drop_table('notifications')
    # ### end Alembic commands ###
