"""Add label field retry

Revision ID: bc9f6062c35c
Revises: 81b8525ff879
Create Date: 2025-12-29 13:28:41.611685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc9f6062c35c'
down_revision: Union[str, None] = '81b8525ff879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    label_enum = sa.Enum('home', 'work', name='labelenum')
    label_enum.create(op.get_bind())
    op.add_column('tasks', sa.Column('label', label_enum, nullable=True))
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='priorityenum'),
               nullable=True,
               existing_server_default=sa.text("'medium'::priorityenum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='priorityenum'),
               nullable=False,
               existing_server_default=sa.text("'medium'::priorityenum"))
    op.drop_column('tasks', 'label')
    sa.Enum('home', 'work', name='labelenum').drop(op.get_bind())
    # ### end Alembic commands ###
